const DEFAULT_QUESTION = 'Where should Phoenix prioritize a cooling intervention this afternoon?';
const TIE_THRESHOLD = 0.1;
const state = { mode: 'replay', requestId: 0, controller: null, map: null, heatLayer: null, markers: new Map(), candidates: [], payload: null, focused: null, focusMode: false };
const $ = (id) => document.getElementById(id);
const text = (el, value) => { if (el) el.textContent = value ?? '—'; };
const num = (value, digits = 1, suffix = '') => value === null || value === undefined || value === '' || Number.isNaN(Number(value)) ? '—' : `${Number(value).toFixed(digits)}${suffix}`;
const coordLabel = (c) => Array.isArray(c) && c.length >= 2 ? `${Number(c[1]).toFixed(4)}°N, ${Math.abs(Number(c[0])).toFixed(4)}°W` : 'Location unavailable';
const titleCase = (s) => String(s || '').replaceAll('_', ' ').replace(/\b\w/g, (m) => m.toUpperCase());

function initMap() {
  if (!window.L || state.map) return;
  state.map = L.map('map', { zoomControl: true, attributionControl: true, preferCanvas: true }).setView([33.4484, -112.074], 12);
  // OpenStreetMap is a no-key fallback; it keeps the demonstration free of API-key watermarks.
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map);
}
function clearMap() { if (!state.map) return; if (state.heatLayer) { state.map.removeLayer(state.heatLayer); state.heatLayer = null; } state.markers.forEach((m) => state.map.removeLayer(m)); state.markers.clear(); const d = $('cell-detail'); if (d) d.hidden = true; }
function featureTemp(feature) { const p = feature?.properties || {}; return Number(p.average_temperature ?? p.temperature_celsius ?? p.temperature ?? p.temp_celsius ?? p.value); }
function colorFor(value, min, max) { const t = max === min ? .5 : Math.max(0, Math.min(1, (value - min) / (max - min))); const stops = ['#f2dfbf', '#e7b06c', '#cf704d', '#9c4539', '#6f302d']; return stops[Math.min(stops.length - 1, Math.floor(t * stops.length))]; }
function renderMap(payload) {
  initMap(); clearMap(); const features = Array.isArray(payload?.heatmap?.features) ? payload.heatmap.features : []; window.__lunaHeatmapFeatureCount = features.length;
  const values = features.map(featureTemp).filter(Number.isFinite); const min = values.length ? Math.min(...values) : null; const max = values.length ? Math.max(...values) : null;
  text($('legend-min'), num(min, 1)); text($('legend-max'), num(max, 1)); if (!features.length) { text($('map-loading'), 'No usable measured field for this mode.'); return; }
  state.heatLayer = L.geoJSON({ type: 'FeatureCollection', features }, { style: (f) => ({ color: 'rgba(255,255,255,.42)', weight: .35, fillColor: colorFor(featureTemp(f), min, max), fillOpacity: .78 }), onEachFeature: (f, layer) => layer.on('click', () => { const d = $('cell-detail'); d.hidden = false; d.replaceChildren(); const label = document.createElement('span'); label.textContent = 'Measured cell'; const strong = document.createElement('strong'); strong.textContent = num(featureTemp(f), 1, '°C'); d.append(label, strong); }) }).addTo(state.map);
  const bounds = state.heatLayer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds.pad(.08)); (payload.ranked_candidates || []).forEach(addMarker);
}
function addMarker(candidate) { if (!state.map || !Array.isArray(candidate.coordinate)) return; const [lon, lat] = candidate.coordinate; if (!Number.isFinite(lat) || !Number.isFinite(lon)) return; const node = document.createElement('span'); node.textContent = candidate.rank; const marker = L.marker([lat, lon], { icon: L.divIcon({ className: `candidate-marker marker-${candidate.rank}`, html: node.outerHTML, iconSize: [30, 30], iconAnchor: [15, 15] }), title: `Candidate ${candidate.rank}` }).addTo(state.map); marker.on('click', () => focusCandidate(candidate.rank, true)); state.markers.set(candidate.rank, marker); }
function focusCandidate(rank, pan = false) { state.focused = Number(rank) > 0 ? Number(rank) : null; document.querySelectorAll('.candidate-card').forEach((card) => card.classList.toggle('focused', Number(card.dataset.rank) === state.focused)); const marker = state.markers.get(state.focused); if (marker && pan && state.map) state.map.panTo(marker.getLatLng()); }
function parkLabel(parks) { if (!parks || parks.available === false) return 'Parks context unavailable'; if (parks.inside_park && typeof parks.inside_park === 'object') return `Inside mapped park${parks.inside_park.park_name ? `: ${parks.inside_park.park_name}` : ''}`; return 'No mapped park at candidate'; }
function renderCandidates(payload) { const list = $('candidate-list'); list.replaceChildren(); const candidates = Array.isArray(payload?.ranked_candidates) ? payload.ranked_candidates : []; state.candidates = candidates; const status = payload?.conditions?.ranking_status; if (!candidates.length) { const empty = document.createElement('p'); empty.className = 'empty-state'; empty.textContent = 'No candidate locations were returned for this mode.'; list.append(empty); return; }
  candidates.forEach((c) => { const card = document.createElement('article'); card.className = `candidate-card ${status === 'near_tie' ? 'near-tie' : ''}`; card.dataset.rank = c.rank; card.tabIndex = 0; card.setAttribute('aria-label', `Candidate ${c.rank}, ${num(c.observed_temp)} degrees Celsius`); card.addEventListener('mouseenter', () => focusCandidate(c.rank)); card.addEventListener('mouseleave', () => focusCandidate(-1)); card.addEventListener('focus', () => focusCandidate(c.rank)); card.addEventListener('click', () => focusCandidate(c.rank, true)); card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); focusCandidate(c.rank, true); } });
    const eyebrow = document.createElement('span'); eyebrow.className = 'eyebrow'; eyebrow.textContent = status === 'near_tie' ? 'TOP THERMAL CLUSTER' : 'THERMAL CANDIDATE'; const h = document.createElement('h3'); h.textContent = `Candidate ${c.rank}`; const rank = document.createElement('span'); rank.className = 'rank'; rank.textContent = String(c.rank).padStart(2, '0'); const temp = document.createElement('div'); temp.className = 'temp'; temp.textContent = num(c.observed_temp, 2, '°C'); const delta = document.createElement('div'); delta.className = 'delta'; delta.textContent = `${num(c.delta_from_area_mean, 2, '°C')} vs area mean`; const divider = document.createElement('hr'); divider.className = 'candidate-divider'; const details = document.createElement('div'); details.className = 'candidate-details'; [['Coordinates', coordLabel(c.coordinate)], ...(state.mode === 'live' ? [['Humidity', num(c.humidity, 0, '%')], ['Heat index', num(c.heat_index, 1, '°C')], ['Apparent temp', num(c.apparent_temp, 1, '°C')] ] : [])].forEach(([label, value]) => { const box = document.createElement('div'); const s = document.createElement('span'); s.textContent = label; const strong = document.createElement('strong'); strong.textContent = value; box.append(s, strong); details.append(box); }); const note = document.createElement('p'); note.className = 'candidate-note'; note.textContent = state.mode === 'replay' ? 'Measured temperature + local context; not a policy prescription.' : 'Environmental parameters retrieved for this candidate in Live mode.'; card.append(eyebrow, h, rank, temp, delta, divider, details, note); list.append(card); }); if (state.mode === 'replay') renderRepresentativeContext(); }
function renderRepresentativeContext() { const root = $('answer-rail'); const existing = $('replay-env-context'); if (existing) existing.remove(); const values = state.replayEnv; if (!values) return; const box = document.createElement('div'); box.id = 'replay-env-context'; box.className = 'ranking-callout'; const strong = document.createElement('strong'); strong.textContent = 'Representative Replay environmental context'; const detail = document.createElement('div'); detail.textContent = `Heat index ${num(values.heat_index, 1, '°C')} · Apparent temperature ${num(values.apparent_temp, 1, '°C')} · Humidity ${num(values.humidity, 0, '%')}`; const disclosure = document.createElement('small'); disclosure.textContent = 'Captured historical context; not independent measurements for each candidate.'; box.append(strong, detail, disclosure); $('ranking-callout')?.after(box); }
function renderContext(payload) { const root = $('context-content'); root.replaceChildren(); const candidates = payload?.ranked_candidates || []; candidates.forEach((c) => { const ctx = c.candidate_context || {}; const canopy = ctx.canopy || {}; const parks = ctx.parks; const row = document.createElement('div'); row.className = 'context-row'; const left = document.createElement('span'); left.textContent = `Candidate ${c.rank}`; const right = document.createElement('strong'); const parts = []; if (canopy.available && canopy.tree_canopy_pct != null) parts.push(`Canopy ${num(canopy.tree_canopy_pct, 1, '%')}`); else if (canopy.available === false) parts.push('Canopy unavailable'); parts.push(parkLabel(parks)); right.textContent = parts.join(' · '); row.append(left, right); root.append(row); }); const disclosure = document.createElement('div'); disclosure.className = 'context-disclosure'; disclosure.textContent = 'Phoenix GIS is local context only (used_in_decision = false). A missing GIS result is not interpreted as “no mapped park.”'; root.append(disclosure); }
function renderBrief(payload) { const root = $('brief-content'); root.replaceChildren(); const brief = payload?.urban_heat_brief; if (!brief) { const p = document.createElement('p'); p.className = 'muted'; p.textContent = 'Brief unavailable because no usable thermal evidence was returned.'; root.append(p); return; } (brief.sections || []).forEach((section) => { const wrap = document.createElement('section'); wrap.className = 'brief-section'; const h = document.createElement('h3'); h.textContent = section.heading; wrap.append(h); (section.claims || []).forEach((claim) => { const item = document.createElement('div'); item.className = 'claim'; const dot = document.createElement('span'); dot.className = 'claim-marker'; const body = document.createElement('div'); body.append(document.createTextNode(claim.text)); const meta = document.createElement('span'); meta.className = 'claim-meta'; meta.textContent = `${claim.source_provider || 'Source unavailable'} · ${claim.used_in_decision ? 'used in decision' : 'context only'}`; body.append(meta); item.append(dot, body); wrap.append(item); }); root.append(wrap); }); }
function renderEvidence(payload) { const root = $('evidence-content'); root.replaceChildren(); (payload?.evidence_chain || []).forEach((node, index) => { const item = document.createElement('div'); item.className = 'chain-node'; const n = document.createElement('b'); n.textContent = String(index + 1).padStart(2, '0'); const body = document.createElement('div'); const h = document.createElement('h3'); h.textContent = titleCase(node.step); const p = document.createElement('p'); const data = node.data || {}; p.textContent = data.provider ? `${data.provider}${data.used_in_decision === false ? ' · context only' : ''}` : data.rationale || data.summary || data.reason || 'Recorded application evidence event.'; const small = document.createElement('small'); small.textContent = node.timestamp || 'timestamp unavailable'; body.append(h, p, small); item.append(n, body); root.append(item); }); }
function setLoading(message, mode) { $('status-region').replaceChildren(); text($('stat-obs-time'), 'Loading…'); text($('observation-note'), message); text($('mode-badge'), mode.toUpperCase()); $('mode-badge').className = `mode-badge ${mode}`; text($('map-source-label'), `FortyGuard · ${mode === 'replay' ? 'Replay' : 'Live'}`); clearMap(); text($('map-loading'), message); }
function showError(payload, mode) { const region = $('status-region'); region.replaceChildren(); const p = document.createElement('p'); const reason = payload?.why_this_answer || payload?.answer?.why_this_answer || payload?.message || ''; p.textContent = mode === 'live' && /last \d+ hours|freshness window|bounded freshness|No usable FortyGuard observation/i.test(reason) ? 'LIVE UNAVAILABLE — No usable FortyGuard observation was available within the bounded freshness window.' : mode === 'live' ? 'LIVE UNAVAILABLE — The current Live request could not be completed.' : 'Unable to load Replay evidence.'; region.append(p); if (mode === 'live') { const button = document.createElement('button'); button.className = 'mode-button'; button.type = 'button'; button.textContent = 'Try Replay'; button.addEventListener('click', () => request('replay')); region.append(button); } }
function render(payload, mode) { state.mode = mode; state.payload = payload; state.replayEnv = payload?.priority_location?.env_params || null; const error = payload?.error === true || payload?.answer?.error === true; if (error) { showError(payload, mode); renderCandidates({ ranked_candidates: [] }); renderBrief({}); renderContext({}); renderEvidence(payload || {}); return; } const conditions = payload.conditions || {}; const ranked = payload.ranked_candidates || conditions.ranked_candidates || []; const observation = payload.observation_time || payload.answer?.observation_time || payload.heatmap?.observation_time; const isNearTie = conditions.ranking_status === 'near_tie'; text($('answer-hero'), ranked.length ? (isNearTie ? `${ranked.length} locations form the top thermal cluster.` : `Start with candidate ${ranked[0].rank}.`) : 'Measured field loaded.'); text($('answer-summary'), payload.summary || payload.answer?.summary || 'Thermal evidence is ready for investigation.'); text($('stat-mean'), num(conditions.area_mean_temperature_celsius, 1, '°C')); text($('stat-range'), num(conditions.area_temperature_range_celsius, 1, '°C')); text($('stat-cells'), conditions.feature_count ?? payload.heatmap?.feature_count ?? '—'); text($('stat-obs-time'), observation || 'Unavailable'); text($('observation-note'), mode === 'replay' ? 'Historical provider capture · reproducible' : 'Latest available provider workflow · time surfaced'); text($('mode-badge'), mode.toUpperCase()); $('mode-badge').className = `mode-badge ${mode}`; text($('map-source-label'), `FortyGuard · ${mode === 'replay' ? 'Replay' : 'Live'}`); const callout = $('ranking-callout'); callout.hidden = !ranked.length; callout.replaceChildren(); if (isNearTie) { const strong = document.createElement('strong'); strong.textContent = 'Near tie · thermal evidence alone does not distinguish'; callout.append(strong, document.createTextNode(` Spread remains within ${num(conditions.tie_threshold_celsius ?? TIE_THRESHOLD, 1, '°C')}. Preserve all candidates as comparable investigation priorities.`)); } else if (ranked.length) { const strong = document.createElement('strong'); strong.textContent = 'Measured ranking'; callout.append(strong, document.createTextNode('Candidate ordering comes from FortyGuard thermal observations only.')); } renderMap(payload); renderCandidates({ ...payload, ranked_candidates: ranked, conditions }); renderContext({ ...payload, ranked_candidates: ranked }); renderBrief(payload); renderEvidence(payload); document.body.classList.add('has-result'); }

const INTENTS = [
  { id: 'mode', keys: ['show live data', 'use live', 'switch to live', 'show replay', 'use replay', 'switch to replay'], answer: () => `Explicit ${state.mode === 'live' ? 'Live' : 'Replay'} mode request received.`, source: 'Mode control · explicit user action required', suggestions: ['Show me the evidence', 'Compare the candidates'] },
  { id: 'priority', keys: ['where', 'hottest', 'top locations', 'priority'], answer: () => `The loaded ${state.mode.toUpperCase()} evidence identifies ${state.candidates.length || 'no'} candidate locations for investigation. FortyGuard measured thermal observations determine the ordering.`, source: 'FortyGuard · measured evidence', suggestions: ['Why are these locations tied?', 'Compare tree canopy', 'Show me the evidence'] },
  { id: 'compare', keys: ['compare', 'different', 'candidates'], answer: () => { const rows = state.candidates.map((c) => `Candidate ${c.rank}: ${num(c.observed_temp, 2, '°C')}, ${num(c.delta_from_area_mean, 2, '°C')} vs area mean`).join(' · '); return rows || 'No candidates are loaded to compare.'; }, source: 'FortyGuard · measured evidence', suggestions: ['Compare canopy', 'Which candidate is in a park?'] },
  { id: 'tie', keys: ['tie', 'winner', 'close'], answer: () => state.payload?.conditions?.ranking_status === 'near_tie' ? `There is no meaningful thermal winner: the top ${state.candidates.length} locations are within the ${num(state.payload.conditions.tie_threshold_celsius ?? TIE_THRESHOLD, 1, '°C')} threshold. Deterministic ranks remain, but all are comparable investigation priorities.` : 'The loaded ranking is not marked as a near tie.', source: 'FortyGuard · measured evidence', suggestions: ['Compare the candidates', 'Show me the evidence'] },
  { id: 'canopy', keys: ['canopy', 'tree cover', 'trees'], answer: () => state.candidates.map((c) => { const value = c.candidate_context?.canopy?.tree_canopy_pct; return `Candidate ${c.rank}: ${value == null ? 'canopy context unavailable' : num(value, 1, '%')}`; }).join(' · ') || 'Canopy context is unavailable.', source: 'Phoenix GIS · context only · not used to rank', action: () => document.querySelector('.context-panel')?.scrollIntoView({ behavior: 'smooth' }), suggestions: ['Which candidates are in mapped parks?', 'Is canopy used to rank them?'] },
  { id: 'parks', keys: ['park', 'parks'], answer: () => state.candidates.map((c) => `Candidate ${c.rank}: ${parkLabel(c.candidate_context?.parks)}`).join(' · ') || 'Park context is unavailable.', source: 'Phoenix GIS · context only · not used to rank', action: () => document.querySelector('.context-panel')?.scrollIntoView({ behavior: 'smooth' }), suggestions: ['Compare canopy', 'Show the measured field'] },
  { id: 'weather', keys: ['nws', 'weather', 'happening now', 'forecast'], answer: () => state.mode === 'replay' ? 'Current NWS context is not included in historical Replay.' : state.payload?.nws_context ? 'NWS provides supplemental current/forecast context; it does not determine the thermal ranking.' : 'NWS supplemental context is unavailable in the loaded result.', source: 'NWS · supplemental context', suggestions: ['Show me the evidence'] },
  { id: 'evidence', keys: ['trust', 'evidence', 'data came', 'provenance'], answer: () => 'The answer is grounded in the loaded evidence chain: FortyGuard measured the thermal field and determines ordering; Phoenix GIS and NWS are contextual and do not re-rank candidates.', source: 'Evidence chain · source roles preserved', action: () => openEvidence(), suggestions: ['Compare the candidates', 'Focus the map'] },
  { id: 'map', keys: ['show candidate', 'focus the map', 'measured cell', 'map'], answer: () => 'The measured FortyGuard field is now the primary surface. Candidate markers remain synchronized with the comparison cards.', source: 'FortyGuard · measured evidence', action: () => { const match = $('question-input').value.match(/candidate\s+(\d+)/i); if (match) focusCandidate(Number(match[1]), true); else setFocusMode(true); }, suggestions: ['Show me the evidence', 'Compare the candidates'] },
  { id: 'unsupported', keys: ['plant', 'planting', 'trees would', 'cool most', 'effect', 'reduce', 'benefit most', 'work best', 'efficacy'], answer: () => 'The current evidence can compare measured heat and available local context, but it does not estimate the cooling effect or efficacy of a specific intervention.', source: 'Governed scope · no intervention efficacy model', suggestions: ['Compare the candidates', 'Show me the evidence'] }
];
function parseIntent(question) { const q = question.toLowerCase(); const unsupported = INTENTS.find((intent) => intent.id === 'unsupported' && intent.keys.some((key) => q.includes(key))); if (unsupported && /(plant|planting|trees would|cool most|cooling effect|reduce|benefit most|how many degrees|work best|efficacy|intervention)/.test(q)) return unsupported; return INTENTS.find((intent) => intent.id !== 'unsupported' && intent.keys.some((key) => q.includes(key))) || INTENTS[0]; }
function runAnalyst(question) { const intent = parseIntent(question); if (intent.id === 'mode') { request(/live/.test(question.toLowerCase()) ? 'live' : 'replay'); } const result = $('analyst-result'); result.replaceChildren(); const label = document.createElement('span'); label.className = 'eyebrow accent'; label.textContent = 'GROUNDED ANALYST'; const answer = document.createElement('p'); answer.textContent = intent.answer(); const source = document.createElement('small'); source.textContent = `Source role: ${intent.source} · ${state.mode.toUpperCase()}`; result.append(label, answer, source); const suggestions = $('analyst-suggestions'); suggestions.replaceChildren(); intent.suggestions.filter((s) => !(state.mode === 'replay' && /NWS|weather|current/i.test(s))).slice(0, 3).forEach((suggestion) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = suggestion; b.addEventListener('click', () => { $('question-input').value = suggestion; runAnalyst(suggestion); }); suggestions.append(b); }); intent.action?.(); }
function openEvidence() { const drawer = $('evidence-drawer'); drawer.hidden = false; $('.evidence-toggle').setAttribute('aria-expanded', 'true'); drawer.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' }); }
function setFocusMode(enabled) { state.focusMode = enabled; document.body.classList.toggle('map-focus', enabled); $('map-focus-button').textContent = enabled ? 'Exit map focus' : 'Focus map'; $('map-focus-button').setAttribute('aria-pressed', String(enabled)); $('focus-exit-layer').hidden = !enabled; $('focus-exit-button').setAttribute('aria-pressed', String(enabled)); if (enabled) $('focus-exit-button').focus(); setTimeout(() => state.map?.invalidateSize(), 20); }
async function request(mode = state.mode) { const id = ++state.requestId; if (state.controller) state.controller.abort(); state.controller = new AbortController(); setLoading(mode === 'replay' ? 'Loading reproducible capture…' : 'Requesting latest available provider observation…', mode); $('btn-replay').classList.toggle('active', mode === 'replay'); $('btn-live').classList.toggle('active', mode === 'live'); $('btn-replay').setAttribute('aria-pressed', String(mode === 'replay')); $('btn-live').setAttribute('aria-pressed', String(mode === 'live')); try { const q = encodeURIComponent($('question-input').value || DEFAULT_QUESTION); const response = await fetch(`/api/answer?question=${q}&mode=${mode}`, { signal: state.controller.signal }); const payload = await response.json(); if (id !== state.requestId) return; render(payload, mode); } catch (error) { if (error.name !== 'AbortError') showError({ message: 'Request unavailable' }, mode); } }
function init() { $('question-input').value = DEFAULT_QUESTION; initMap(); $('question-form').addEventListener('submit', (e) => { e.preventDefault(); const q = $('question-input').value.trim(); if (q && q !== DEFAULT_QUESTION) runAnalyst(q); else request(state.mode); }); $('btn-replay').addEventListener('click', () => request('replay')); $('btn-live').addEventListener('click', () => request('live')); $('map-focus-button').addEventListener('click', () => setFocusMode(!state.focusMode)); $('focus-exit-button').addEventListener('click', () => setFocusMode(false)); document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && state.focusMode) { e.preventDefault(); setFocusMode(false); $('map-focus-button').focus(); } }); $('evidence-close').addEventListener('click', () => { $('evidence-drawer').hidden = true; $('.evidence-toggle').setAttribute('aria-expanded', 'false'); }); $('.evidence-toggle').addEventListener('click', openEvidence); request('replay'); }
window.addEventListener('DOMContentLoaded', init);
