const DEFAULT_QUESTION = 'Where should Phoenix prioritize a cooling intervention this afternoon?';
const TIE_THRESHOLD = 0.1;
const state = { mode: 'replay', requestId: 0, controller: null, map: null, heatLayer: null, markers: new Map(), candidates: [] };
const LEAFLET_CDN = 'https://unpkg.com/leaflet@1.9.4';
const $ = (id) => document.getElementById(id);
const text = (el, value) => { if (el) el.textContent = value ?? '—'; };
const num = (value, digits = 1, suffix = '') => value === null || value === undefined || value === '' || Number.isNaN(Number(value)) ? '—' : `${Number(value).toFixed(digits)}${suffix}`;
const coordLabel = (c) => Array.isArray(c) && c.length >= 2 ? `${Number(c[1]).toFixed(4)}°N, ${Math.abs(Number(c[0])).toFixed(4)}°W` : 'Location unavailable';
const titleCase = (s) => String(s || '').replaceAll('_', ' ').replace(/\b\w/g, (m) => m.toUpperCase());

function initMap() {
  if (!window.L || state.map) return;
  state.map = L.map('map', { zoomControl: true, attributionControl: true, preferCanvas: true }).setView([33.4484, -112.074], 12);
  L.tileLayer('https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap &copy; CARTO' }).addTo(state.map);
}
function clearMap() {
  if (!state.map) return;
  if (state.heatLayer) { state.map.removeLayer(state.heatLayer); state.heatLayer = null; }
  state.markers.forEach((m) => state.map.removeLayer(m)); state.markers.clear();
  const detail = $('cell-detail'); if (detail) detail.hidden = true;
}
function colorFor(value, min, max) {
  const t = max === min ? .5 : Math.max(0, Math.min(1, (value - min) / (max - min)));
  const stops = ['#f2dfbf', '#e7b06c', '#cf704d', '#9c4539', '#6f302d'];
  return stops[Math.min(stops.length - 1, Math.floor(t * stops.length))];
}
function featureTemp(feature) {
  const p = feature?.properties || {};
  return Number(p.temperature_celsius ?? p.temperature ?? p.temp_celsius ?? p.value);
}
function renderMap(payload) {
  initMap(); clearMap();
  const features = Array.isArray(payload?.heatmap?.features) ? payload.heatmap.features : [];
  const values = features.map(featureTemp).filter(Number.isFinite);
  const min = values.length ? Math.min(...values) : null, max = values.length ? Math.max(...values) : null;
  text($('legend-min'), num(min, 1)); text($('legend-max'), num(max, 1));
  if (!features.length) { $('map').querySelector('.map-loading').textContent = 'No usable measured field for this mode.'; return; }
  const collection = { type: 'FeatureCollection', features };
  state.heatLayer = L.geoJSON(collection, { style: (f) => ({ color: 'rgba(255,255,255,.42)', weight: .35, fillColor: colorFor(featureTemp(f), min, max), fillOpacity: .78 }), onEachFeature: (f, layer) => layer.on('click', () => { const value = featureTemp(f); const d = $('cell-detail'); d.hidden = false; d.textContent = 'Measured cell'; const strong = document.createElement('strong'); strong.textContent = num(value, 1, '°C'); d.append(strong); }) }).addTo(state.map);
  const bounds = state.heatLayer.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds.pad(.08));
  (payload.ranked_candidates || []).forEach((candidate) => addMarker(candidate));
}
function addMarker(candidate) {
  if (!state.map || !Array.isArray(candidate.coordinate)) return;
  const [lon, lat] = candidate.coordinate; if (!Number.isFinite(lat) || !Number.isFinite(lon)) return;
  const marker = L.marker([lat, lon], { icon: L.divIcon({ className: `candidate-marker marker-${candidate.rank}`, html: (() => { const node = document.createElement('span'); node.textContent = candidate.rank; return node.outerHTML; })(), iconSize: [30, 30], iconAnchor: [15, 15] }), title: `Candidate ${candidate.rank}` }).addTo(state.map);
  marker.on('click', () => focusCandidate(candidate.rank, true)); state.markers.set(candidate.rank, marker);
}
function focusCandidate(rank, pan = false) { document.querySelectorAll('.candidate-card').forEach((card) => card.classList.toggle('focused', Number(card.dataset.rank) === Number(rank))); const marker = state.markers.get(Number(rank)); if (marker && pan) state.map.panTo(marker.getLatLng()); }
function renderCandidates(payload) {
  const list = $('candidate-list'); list.replaceChildren(); const candidates = Array.isArray(payload?.ranked_candidates) ? payload.ranked_candidates : []; state.candidates = candidates;
  const status = payload?.conditions?.ranking_status; if (!candidates.length) { const empty = document.createElement('p'); empty.className = 'empty-state'; empty.textContent = 'No candidate locations were returned for this mode.'; list.append(empty); return; }
  candidates.forEach((c) => { const card = document.createElement('article'); card.className = `candidate-card ${status === 'near_tie' ? 'near-tie' : ''}`; card.dataset.rank = c.rank; card.tabIndex = 0; card.setAttribute('aria-label', `Candidate ${c.rank}, ${num(c.observed_temp)} degrees Celsius`); card.addEventListener('mouseenter', () => focusCandidate(c.rank)); card.addEventListener('mouseleave', () => focusCandidate(-1)); card.addEventListener('focus', () => focusCandidate(c.rank)); card.addEventListener('click', () => focusCandidate(c.rank, true)); card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); focusCandidate(c.rank, true); } });
    const eyebrow = document.createElement('span'); eyebrow.className = 'eyebrow'; eyebrow.textContent = status === 'near_tie' ? 'TOP THERMAL CLUSTER' : 'THERMAL CANDIDATE'; card.append(eyebrow);
    const h = document.createElement('h3'); h.textContent = `Candidate ${c.rank}`; card.append(h); const rank = document.createElement('span'); rank.className = 'rank'; rank.textContent = String(c.rank).padStart(2, '0'); card.append(rank);
    const temp = document.createElement('div'); temp.className = 'temp'; temp.textContent = num(c.observed_temp, 2, '°C'); card.append(temp); const delta = document.createElement('div'); delta.className = 'delta'; delta.textContent = `${num(c.delta_from_area_mean, 2, '°C')} vs area mean`; card.append(delta); card.append(document.createElement('hr')).className = 'candidate-divider';
    const details = document.createElement('div'); details.className = 'candidate-details'; [['Coordinates', coordLabel(c.coordinate)], ['Humidity', num(c.humidity, 0, '%')], ['Heat index', num(c.heat_index, 1, '°C')], ['Apparent temp', num(c.apparent_temp, 1, '°C')]].forEach(([label, value]) => { const box = document.createElement('div'); const s = document.createElement('span'); s.textContent = label; const strong = document.createElement('strong'); strong.textContent = value; box.append(s, strong); details.append(box); }); card.append(details);
    const note = document.createElement('p'); note.className = 'candidate-note'; note.textContent = state.mode === 'replay' ? 'Environmental values are representative Replay context, not independent candidate measurements.' : 'Environmental parameters retrieved for this candidate in Live mode.'; card.append(note); list.append(card); });
}
function renderContext(payload) {
  const root = $('context-content'); root.replaceChildren(); const candidates = payload?.ranked_candidates || []; if (!candidates.length) { const p = document.createElement('p'); p.className = 'muted'; p.textContent = 'No candidate context available.'; root.append(p); return; }
  candidates.forEach((c) => { const ctx = c.candidate_context || {}; const canopy = ctx.canopy || {}; const parks = ctx.parks || {}; const row = document.createElement('div'); row.className = 'context-row'; const left = document.createElement('span'); left.textContent = `Candidate ${c.rank}`; const right = document.createElement('strong'); const parts = []; if (canopy.available && canopy.tree_canopy_pct != null) parts.push(`Canopy ${num(canopy.tree_canopy_pct, 1, '%')}`); else if (ctx.canopy && ctx.canopy.available === false) parts.push('Canopy unavailable'); if (parks.available && parks.inside_park != null) parts.push(parks.inside_park ? 'Inside mapped park' : 'Outside mapped park'); else if (ctx.parks && ctx.parks.available === false) parts.push('Parks unavailable'); right.textContent = parts.join(' · ') || 'Context unavailable'; row.append(left, right); root.append(row); });
  const disclosure = document.createElement('div'); disclosure.className = 'context-disclosure'; disclosure.textContent = 'Phoenix GIS is local context only (used_in_decision = false). A missing GIS result is not interpreted as “no mapped park.”'; root.append(disclosure);
}
function renderBrief(payload) {
  const root = $('brief-content'); root.replaceChildren(); const brief = payload?.urban_heat_brief; if (!brief) { const p = document.createElement('p'); p.className = 'muted'; p.textContent = 'Brief unavailable because no usable thermal evidence was returned.'; root.append(p); return; }
  (brief.sections || []).forEach((section) => { const wrap = document.createElement('section'); wrap.className = 'brief-section'; const h = document.createElement('h3'); h.textContent = section.heading; wrap.append(h); (section.claims || []).forEach((claim) => { const item = document.createElement('div'); item.className = 'claim'; const dot = document.createElement('span'); dot.className = 'claim-marker'; const body = document.createElement('div'); body.append(document.createTextNode(claim.text)); const meta = document.createElement('span'); meta.className = 'claim-meta'; meta.textContent = `${claim.source_provider || 'Source unavailable'} · ${claim.used_in_decision ? 'used in decision' : 'context only'}`; body.append(meta); item.append(dot, body); wrap.append(item); }); root.append(wrap); });
}
function renderEvidence(payload) {
  const root = $('evidence-content'); root.replaceChildren(); const chain = Array.isArray(payload?.evidence_chain) ? payload.evidence_chain : []; if (!chain.length) { const p = document.createElement('p'); p.className = 'muted'; p.textContent = 'No evidence events returned.'; root.append(p); return; } chain.forEach((node, index) => { const item = document.createElement('div'); item.className = 'chain-node'; const n = document.createElement('b'); n.textContent = String(index + 1).padStart(2, '0'); const body = document.createElement('div'); const h = document.createElement('h3'); h.textContent = titleCase(node.step); const p = document.createElement('p'); const data = node.data || {}; const summary = data.provider ? `${data.provider}${data.used_in_decision === false ? ' · context only' : ''}` : data.rationale || data.summary || data.reason || 'Recorded application evidence event.'; p.textContent = summary; const small = document.createElement('small'); small.textContent = node.timestamp || 'timestamp unavailable'; body.append(h, p, small); item.append(n, body); root.append(item); }); }
function setLoading(message, mode) { $('status-region').replaceChildren(); text($('stat-obs-time'), 'Loading…'); text($('observation-note'), message); $('mode-badge').textContent = mode.toUpperCase(); $('mode-badge').className = `mode-badge ${mode}`; $('map-source-label').textContent = `FortyGuard · ${mode === 'replay' ? 'Replay' : 'Live'}`; clearMap(); $('map').querySelector('.map-loading').textContent = message; }
function render(payload, mode) { state.mode = mode; const error = payload?.error || payload?.message || payload?.answer?.error; if (error) { const region = $('status-region'); const p = document.createElement('p'); p.textContent = mode === 'live' ? 'LIVE UNAVAILABLE — No usable FortyGuard observation was available within the bounded freshness window.' : 'Unable to load Replay evidence.'; region.append(p); if (mode === 'live') { const button = document.createElement('button'); button.className = 'mode-button'; button.type = 'button'; button.textContent = 'Try Replay'; button.addEventListener('click', () => request('replay')); region.append(button); } renderCandidates({}); renderBrief({}); renderContext({}); renderEvidence(payload || {}); return; }
  $('status-region').replaceChildren(); const conditions = payload.conditions || {}; const ranked = payload.ranked_candidates || conditions.ranked_candidates || []; text($('answer-hero'), ranked.length ? `Start with candidate ${ranked[0].rank}.` : 'Measured field loaded.'); text($('answer-summary'), payload.summary || 'Thermal evidence is ready for investigation.'); text($('stat-mean'), num(conditions.area_mean_temperature_celsius, 1, '°C')); text($('stat-range'), num(conditions.area_temperature_range_celsius, 1, '°C')); text($('stat-cells'), conditions.feature_count ?? payload.heatmap?.feature_count ?? '—'); text($('stat-obs-time'), payload.observation_time || payload.heatmap?.observation_time || 'Unavailable'); text($('observation-note'), mode === 'replay' ? 'Historical provider capture · reproducible' : 'Latest available provider workflow · time surfaced'); $('mode-badge').textContent = mode.toUpperCase(); $('mode-badge').className = `mode-badge ${mode}`; $('map-source-label').textContent = `FortyGuard · ${mode === 'replay' ? 'Replay' : 'Live'}`; const callout = $('ranking-callout'); callout.hidden = !ranked.length; callout.replaceChildren(); if (conditions.ranking_status === 'near_tie') { const strong = document.createElement('strong'); strong.textContent = 'Near tie · thermal evidence alone does not distinguish'; callout.append(strong, document.createTextNode(` Spread remains within ${num(conditions.tie_threshold_celsius ?? TIE_THRESHOLD, 1, '°C')}. Preserve all candidates as comparable investigation priorities.`)); } else if (ranked.length) { const strong = document.createElement('strong'); strong.textContent = 'Measured ranking'; callout.append(strong, document.createTextNode('Candidate ordering comes from FortyGuard thermal observations only.')); } renderMap(payload); renderCandidates({ ...payload, ranked_candidates: ranked }); renderContext({ ...payload, ranked_candidates: ranked }); renderBrief(payload); renderEvidence(payload); }
async function request(mode = state.mode) { const id = ++state.requestId; if (state.controller) state.controller.abort(); state.controller = new AbortController(); setLoading(mode === 'replay' ? 'Loading reproducible capture…' : 'Requesting latest available provider observation…', mode); $('btn-replay').classList.toggle('active', mode === 'replay'); $('btn-live').classList.toggle('active', mode === 'live'); $('btn-replay').setAttribute('aria-pressed', String(mode === 'replay')); $('btn-live').setAttribute('aria-pressed', String(mode === 'live')); try { const q = encodeURIComponent($('question-input').value || DEFAULT_QUESTION); const response = await fetch(`/api/answer?question=${q}&mode=${mode}`, { signal: state.controller.signal }); const payload = await response.json(); if (id !== state.requestId) return; render(payload, mode); } catch (error) { if (error.name === 'AbortError') return; render({ error: true, message: 'Request unavailable' }, mode); } }
function init() { $('question-input').value = DEFAULT_QUESTION; initMap(); $('question-form').addEventListener('submit', (e) => { e.preventDefault(); request(state.mode); }); $('btn-replay').addEventListener('click', () => request('replay')); $('btn-live').addEventListener('click', () => request('live')); const drawer = $('evidence-drawer'); $('evidence-close').addEventListener('click', () => { drawer.hidden = true; $('.evidence-toggle').setAttribute('aria-expanded', 'false'); }); document.querySelector('.evidence-toggle').addEventListener('click', () => { drawer.hidden = !drawer.hidden; document.querySelector('.evidence-toggle').setAttribute('aria-expanded', String(!drawer.hidden)); if (!drawer.hidden) drawer.scrollIntoView({ behavior: 'smooth', block: 'start' }); }); request('replay'); }
window.addEventListener('DOMContentLoaded', init);
